services:
  migration:
    container_name: migration
    build:
      context: ./orchestrator
      dockerfile: Dockerfile.migrations
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["sh", "-c", "sleep 4 && uv run alembic upgrade head"]

  orchestrator:
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy
