"""add base schemas

Revision ID: 17bbb767e50b
Revises: 
Create Date: 2026-05-15 09:40:22.850611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bbb767e50b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gpu_type', sa.Enum('L40S', 'H100', name='gputype'), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('provisioning', 'busy', 'down', name='nodestatus'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('current_run_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'provisioning', 'running', 'done', 'failed', name='runstatus'), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('model_size_b', sa.Integer(), nullable=False),
    sa.Column('engine', sa.Enum('vllm', 'llamacpp', name='engine'), nullable=False),
    sa.Column('gpu_type_required', sa.Enum('L40S', 'H100', name='gputype'), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('scenario_path', sa.String(), nullable=False),
    sa.Column('gguf_file', sa.String(), nullable=True),
    sa.Column('results_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('gpu_type', sa.Enum('L40S', 'H100', name='gputype'), nullable=False),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('ttft_mean_s', sa.Float(), nullable=False),
    sa.Column('ttft_median_s', sa.Float(), nullable=False),
    sa.Column('ttft_p95_s', sa.Float(), nullable=False),
    sa.Column('tpot_mean_s', sa.Float(), nullable=False),
    sa.Column('e2e_mean_s', sa.Float(), nullable=False),
    sa.Column('e2e_p95_s', sa.Float(), nullable=False),
    sa.Column('tokens_per_second_mean', sa.Float(), nullable=False),
    sa.Column('total_tokens_per_second', sa.Float(), nullable=False),
    sa.Column('requests_per_second', sa.Float(), nullable=False),
    sa.Column('total_duration_s', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('runs')
    op.drop_table('nodes')
    # ### end Alembic commands ###
